=== ICI-ESPORT1/E-sports/Lenguaje de Marcas/UltimaJornada/ultimaJorn.dtd
<!ELEMENT ultimaJorn (jornada)>
    <!ELEMENT jornada (partido+)>
    <!ELEMENT partido (equipo+)>
    <!ELEMENT equipo (nombre,resultado)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT resultado (#PCDATA)>
    <!ATTLIST jornada numJornada CDATA #REQUIRED>
    <!ATTLIST partido idPartido CDATA #REQUIRED>

=== ICI-ESPORT1/E-sports/Base de Datos/script/Tablas/Lenguaje de Marcas/UltimaJornada/ultimaJorn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ultimaJorn 
    SYSTEM "ultimaJorn.dtd"
    >
<ultimaJorn>
<jornada numJornada="01">
        <partido idPartido="01">
            <equipo>
               <nombre>uno</nombre>
               <resultado>g</resultado>
            </equipo>
            <equipo>
               <nombre>dos</nombre>
               <resultado>p</resultado>
            </equipo> 
        </partido>
        <partido idPartido="02">
            <equipo>
               <nombre>tres</nombre>
               <resultado>g</resultado>
            </equipo>
            <equipo>
               <nombre>cuatro</nombre>
               <resultado>p</resultado>
            </equipo> 
        </partido>
        <partido idPartido="03">
            <equipo>
               <nombre>uno</nombre>
               <resultado>p</resultado>
            </equipo>
            <equipo>
               <nombre>cinco</nombre>
               <resultado>g</resultado>
            </equipo> 
        </partido>
</jornada>
</ultimaJorn>
