=== ICI-ESPORT1/E-sports/Lenguaje de Marcas/XML_CLA/clasificacion2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clasificacion" type="clasificacionType"/>
  <xs:complexType name="equipoType">
    <xs:sequence>
      <xs:element type="xs:string" name="nombre"/>
      <xs:element type="xs:string" name="puntos"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="clasificacionType">
    <xs:sequence>
      <xs:element type="equipoType" name="equipo" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ICI-ESPORT1/E-sports/Lenguaje de Marcas/XML_CLA/clasificacion2.xml
<?xml version="1.0" encoding="UTF-8"?>
<clasificacion
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:noNamespaceSchemaLocation="clasificacion2.xsd">

    <equipo id="01" >
        <nombre></nombre>
        <puntos></puntos>
    </equipo>

    <equipo id="02">
        <nombre></nombre>
        <puntos></puntos>
    </equipo>

    <equipo id="03">
        <nombre></nombre>
        <puntos></puntos>
    </equipo>

</clasificacion>
