=== ICI-ESPORT1/E-sports/Lenguaje de Marcas/Resultados/resultados.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT resumenResultados (jornada+)>
    <!ELEMENT jornada (partido+)>
    <!ELEMENT partido (equipo+)>
    <!ELEMENT equipo (nombre,resultado)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT resultado (#PCDATA)>
    <!ATTLIST jornada numJornada CDATA #REQUIRED>
    <!ATTLIST partido idPartido CDATA #REQUIRED>

=== ICI-ESPORT1/E-sports/Base de Datos/script/Tablas/Lenguaje de Marcas/Resultados/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resumenResultados 
    SYSTEM "resultados.dtd"
>
<!-- Resultados.xml, Para guardar los resultados de todas las jornadas-->
<resumenResultados>
<jornada numJornada="01">
        <partido idPartido="01">
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo>
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo> 
        </partido>
        <partido idPartido="02">
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo>
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo> 
        </partido>
        <partido idPartido="03">
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo>
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo> 
        </partido>
</jornada>
<jornada numJornada="02">
        <partido idPartido="04">
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo>
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo> 
        </partido>
        <partido idPartido="05">
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo>
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo> 
        </partido>
        <partido idPartido="06">
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo>
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo> 
        </partido>
        <partido idPartido="06">
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo>
            <equipo>
               <nombre></nombre>
               <resultado></resultado>
            </equipo> 
        </partido>
</jornada>
</resumenResultados>
