=== ICI-ESPORT1/E-sports/Base de Datos/script/Tablas/Lenguaje de Marcas/XML_CLA/clasificacion.dtd
<!ELEMENT clasificacion (equipo)+>
        <!ELEMENT equipo (nombre,puntos)>
        <!ATTLIST equipo id CDATA #IMPLIED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT puntos (#PCDATA)>

=== ICI-ESPORT1/E-sports/Base de Datos/script/Tablas/Lenguaje de Marcas/XML_CLA/clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clasificacion
        SYSTEM "clasificacion.dtd"
        >
<clasificacion>
    <equipo id="01" >
        <nombre></nombre>
        <puntos></puntos>
    </equipo>

    <equipo id="02">
        <nombre></nombre>
        <puntos></puntos>
    </equipo>

    <equipo id="03">
        <nombre></nombre>
        <puntos></puntos>
    </equipo>

</clasificacion>
